### ISSUE TITLE
AppImage release

### ISSUE THREAD

**Issue by cobalt2727** [ryujinx-mirror/ryujinx#15]
Would be nice to have something I can easily drop in as a replacement on my Steam Deck (among other things).

**Comment by Samueru-sama** [comment]
I can help here, all that would need to be done is turned the portable linux binaries into an appimage, [like I used to do here](https://github.com/Samueru-sama/Ryujinx-AppImage/blob/main/ryujinx-appimage.sh).

**Comment by regginator** [comment]
Resolved with #28, added to the release workflow in https://github.com/ryujinx-mirror/ryujinx/commit/9c5dda18485a7968af59c138d6cd8128ff8816dc ! Additional thanks to @Samueru-sama for the help.
