### ISSUE TITLE
Maintainer updated release to promote their Roblox Discord server

### ISSUE THREAD

**Issue by schwizzlers** [ryujinx-mirror/ryujinx#23]
The Discord social link in the latest release has been changed to "Latte Softworks" which seems to be some random Roblox-related server with a target audience of teenagers. I tried checking the server for anything emulator related and the only thing is a mod comment in an announcement channel mentioning they're maintaining this fork.

Avoid latest release.

**Comment by TheGreatSageEqualToHeaven** [comment]
![image](https://github.com/user-attachments/assets/549a76a8-be86-44a4-9a91-795fc8f56abb)

/shrug

**Comment by regginator** [comment]
[Latte Softworks](https://latte.to) is our organization, I am currently working on getting a few more important things done first, though the intention was to have a channel setup in Latte specifically surrounding development of this repository. I can only do a couple of things at a time :slightly_smiling_face:

P.S., Latte Softworks is not a Roblox-specific community, though we do maintain a few other projects completely separate from this.

**Comment by regginator** [comment]
To add on to the fact that we're not a Roblox-specific community, take a look at our latest announcement! (Besides this fork, of course..)

![image](https://github.com/user-attachments/assets/08bcbedb-f8ce-4688-a0ac-f476294c648b)

**Comment by enbyte** [comment]
@regginator are you intending to be a dev for the project, or just host the mirror here and people will contrib?

**Comment by regginator** [comment]
> @regginator are you intending to be a dev for the project, or just host the mirror here and people will contrib?

*I* am primarily working on build infrastructure & minor fixes at this very moment, though I will also be accepting non-major changes while a few things are still up in the air as far as the whole of Ryujinx goes..

I am **open** to the idea of maintaining in some form soon, but again, there are a few other things I need to get done first :sweat_smile:

**Comment by enbyte** [comment]
Seems cool. I will work on contrib + trying to find any archives of documentation that I can for contributing beyond the style guide.

**Comment by regginator** [comment]
I have mentioned this before, but I do want to eventually migrate over the original wiki from the `Ryujinx/Ryujinx` repository, though I am hesitant due to what happened with Yuzu back in March..

**Comment by enbyte** [comment]
Ryujinx wiki was clean right? No mentions of piracy and reveng is 100% protected under DMCA

**Comment by regginator** [comment]
> Ryujinx wiki was clean right? No mentions of piracy and reveng is 100% protected under DMCA

I believe so, yes. Also, looks like @Trigus42 has already given us a MASSIVE head start with #24!
