### ISSUE TITLE
[Feature Request] NSZ and XCZ support.

### ISSUE THREAD

**Issue by TimeFlex1** [ryujinx-mirror/ryujinx#36]
Could we get support for the most common compression filetypes for Switch emulation? Would like the keep my games compressed on my external and just play them without decompressing the games first. Some games are half the file size in compressed format. Please!

**Comment by amurgshere** [comment]
Hey @TimeFlex1 ,

The XCI formats probably compress to XCZ so well because a lot of the space in the XCI files is just padding, I have create a branch and pull request for a new trim feature which will trim XCI files allowing for the smaller size without the compression. decompression performance overheads. You might want to download that version and try out the trimming instead while this feature is still being considered.

Thank You.

**Comment by LokeYourC3PH** [comment]
> Hey @TimeFlex1 ,
> 
> The XCI formats probably compress to XCZ so well because a lot of the space in the XCI files is just padding, I have create a branch and pull request for a new trim feature which will trim XCI files allowing for the smaller size without the compression. decompression performance overheads. You might want to download that version and try out the trimming instead while this feature is still being considered.
> 
> Thank You.

Thank god someone is working on it, I really hated the hesitancy and outright dismissal at times of old RyujiNX and Yuzu devs to include NSZ and XCZ support with the usual canned reply of "don't need it, nobody uses it", when that obviously wasn't back then and still now isn't true. So thank you for actually considering it 🙏

**Comment by amurgshere** [comment]
@LokeYourC3PH ,

The support for these files would only be worth if they support block level compression, which would enable the emulator to play games from them on the fly without having to first extract the entire ROM. 

This information here:

https://gbatemp.net/threads/nszip-nsp-compressor-decompressor-to-reduce-storage.530313/

References a format of XCZ and NSZ that does support Block level compression

NSZ/XCZ:
- GitHub Project: https://github.com/nicoboss/nsz
- Uses solid compression by default. Block compression can be enabled using the -B option. Block compression will be the default for XCZ
- Decrypts all sections while keeping the first 0x4000 bytes encrypted. Puts informations needed to encrypt inside the header.
- Deleted NDV0 fragments as they have no use for end users as they only exist to save CDN bandwidth
- Already widely used. Supported by Tinfoil, SX Installer v3.0.0 and probably a lot of other software in the future

I think implementing the Block compression would be possible, as a Stream wrapper could be written around the file stream. This stream wrapper could decompress the blocks on an as needed basis and even potentially cache blocks that are being hit more often.

But keep in mind it could only support the formats that use block compression, and only if the block compression is implemented in a way that allows random seeking to the original file position.

**Comment by extherian** [comment]
Out of curiosity, wouldn't this require XCIs to be decrypted first? How is it possible to compress an image full of redundant, encrypted data? Or does it decrypt the XCI, compress it, then reencrypt it again?

**Comment by ryzendew** [comment]
This was rejected because it would take more CPU power and require things to be decompressed on the fly and it could hurt performance as well.

**Comment by amurgshere** [comment]
Thanks @ryzendew , if the performance hit is significant then I would absolutely agree, do you know what the estimated performance hit was like using a block method of compression / decompression?

**Comment by woolrage** [comment]
I´d also love to have the feature to use NSZ even without block level compression. For me it does not matter that I have to wait even minutes at game start when I can have my collection as small as possible in return. Having support for NSZ with block level compression would of course be perfect.

**Comment by GreemDev** [comment]
Recommend against supporting NSZ.
Not only does it come with an overhead it would just enable piracy.
This is why NSZ was never supported in Ryujinx in the first place.

**Comment by woolrage** [comment]
I think NSP/XCI support also enables piracy, right? ;))

**Comment by GreemDev** [comment]
> I think NSP/XCI support also enables piracy, right? ;))

Are you stupid or just being funny

**Comment by woolrage** [comment]
funny
