### ISSUE TITLE
[Bug] Crashes in Mario Party Jamboree after daily challenge.

### ISSUE THREAD

**Issue by smiRaphi** [ryujinx-mirror/ryujinx#44]
### Description of the issue

Crashes after winning a daily mingame challenge in Super Mario Party Jamboree after starting the game for the first time, it didn't crash after restarting the emulator and finishing another daily challenge.

### Reproduction steps

Start the game for the first time, go to minigame bay and win a daily challenge.

### Log file

[Ryujinx_r.b4cac89_2024-10-12_22-09-56.log](https://github.com/user-attachments/files/17351572/Ryujinx_r.b4cac89_2024-10-12_22-09-56.log)

### OS

Windows 11

### Ryujinx version (revision hash)

rb4cac89

### Game version

1.1.0

### CPU

R9 7950x3D

### GPU

Nvidia RTX 4090

### RAM

96GB

**Comment by JaCkperByte** [comment]
**BEWARE piracy**, the game launches 17/OCT.

**Comment by smiRaphi** [comment]
I preordered it on amazon and it already got delivered, had that happened to a few games but usually only a day or 2

**Comment by JaCkperByte** [comment]
my apologies... 
now i freak out easily..

**Comment by regginator** [comment]
Regardless, we cannot support titles leaked before their official release dates whatsoever, apologies.
