### ISSUE TITLE
[Feature] add labels for the compatibility list

### ISSUE THREAD

**Issue by Eli0t77** [ryujinx-mirror/ryujinx#46]
heres a list of labels from the original project

crash
status-nothing
status-boots
status-menus
status-ingame
status-playable
gpu
incomplete
audio
services
slow
amd-vendor-bug
intel-vendor-bug
ldn-working
ldn-broken
online-working
macos-bug

found this site of old compatibility issues but its all in one long page
https://git.chanpinqingbaoju.com/ryujinx/ryujinx-games-list

and a few pages from archive.md
https://archive.md/https://github.com/Ryujinx/Ryujinx-Games-List/issues

**Comment by regginator** [comment]
Awesome, will add these, thanks!

**Comment by regginator** [comment]
Hopefully this is somewhat accurate for now https://github.com/ryujinx-mirror/ryujinx-games-list/issues/

![image](https://github.com/user-attachments/assets/c88f82a9-5b4c-4d27-b095-78116a8ef6ff)
