### ISSUE TITLE
Malware on commit 6253fe1?

### ISSUE THREAD

**Issue by JS299990** [ryujinx-mirror/ryujinx#96]
I ended up having to use a download manager to be able to get the file because every time I tried downloading it while on a browser it would just get rid of it automatically, and I kept getting a "virus detected" error. So I uploaded the .exe to VirusTotal and these are the [results](https://www.virustotal.com/gui/file/3a396152e30a5ef4f55e21100214a61916c8e71838a44a2fa1e427322081cb83)

I don't know what to make of it, there are always false positives but no matter what browser I use, it would just get rid of the file, not to mention my antivirus wasn't having it either

This is worrying so I would just like some reassurance

**Comment by GreemDev** [comment]
The project is open source & you are able to audit the code, not to mention you can decompile the binary yourself via something like [dotPeek](https://www.jetbrains.com/decompiler/).

**Comment by JS299990** [comment]
> The project is open source & you are able to audit the code, not to mention you can decompile the binary yourself via something like [dotPeek](https://www.jetbrains.com/decompiler/).

I understand, but I'm not a programmer though, I can't actually understand code. It's just that seeing these warnings made me worried
